# This is a basic workflow that is manually triggered

name: Operator Build

on:
  push:
    branches: [main, vnext]
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-operator:
    # The type of runner that the job will run on
    runs-on: centos8-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ secrets.TEST_VALUE }}"
