# This is a basic workflow that is manually triggered

name: Operator Build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-operator:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Check secret
        run: echo "Hello ${{ secrets.TEST_VALUE }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: echo "OPERATOR_VERSION=$(cat helm-charts/verticadb-operator/Chart.yaml | awk  '/^version/ {print $2}')" >> $GITHUB_ENV

      - name: Check Operator Version
        run: echo "Operator Version - ${OPERATOR_VERSION}"

      # setup Docker buld action
      - name: Call makefile
        run: make docker-build-operator TAG="${OPERATOR_VERSION}-${GITHUB_RUN_NUMBER}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Push Docker Image
        - run: |
           docker tag verticadb-operator:${OPERATOR_VERSION} "${{secrets.DOCKERHUB_OPERATOR_REPO}}":"${OPERATOR_VERSION}-${GITHUB_RUN_NUMBER}"
           docker tag verticadb-operator:${OPERATOR_VERSION} "${{secrets.DOCKERHUB_OPERATOR_REPO}}":latest
           docker images