# This is a basic workflow that is manually triggered

name: Trigger int tests

on:
  repository_dispatch:
    types: [custom_event_type]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-operator:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Check secret
        run: echo "Hello ${{ secrets.TEST_VALUE }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check parameters
        run: echo "Hello ${{ github.event.client_payload.TAG }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Pull vertica-k8s image
        run: docker pull verticadocker/vertica-k8s-private:${{ github.event.client_payload.TAG }}

      - name: Modify Kustomize.cfg
        run: |
          sed -i 's-^PRIVATE_REG_SERVER=-&https://index.docker.io/v1/-' tests/kustomize-defaults.cfg
          sed -i 's-^PRIVATE_REG_USERNAME=-${{ secrets.DOCKERHUB_USER }}-' tests/kustomize-defaults.cfg
          sed -i 's-^PRIVATE_REG_PASSWORD=-${{ secrets.DOCKERHUB_PASS }}-' tests/kustomize-defaults.cfg

      



      


      


      

      
          
